--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.admin___emoji___import_zip_request
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("admin___emoji___import_zip_request", function()
  local openapiclient_admin___emoji___import_zip_request = require "openapiclient.model.admin___emoji___import_zip_request"

  -- unit tests for the property 'file_id'
  describe("property file_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
