--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.emoji_detailed_admin_role_ids_that_can_be_used_this_emoji_as_reaction_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("emoji_detailed_admin_role_ids_that_can_be_used_this_emoji_as_reaction_inner", function()
  local openapiclient_emoji_detailed_admin_role_ids_that_can_be_used_this_emoji_as_reaction_inner = require "openapiclient.model.emoji_detailed_admin_role_ids_that_can_be_used_this_emoji_as_reaction_inner"

  -- unit tests for the property 'id'
  describe("property id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'name'
  describe("property name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
