--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.i___2fa___register_key_200_response_user
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("i___2fa___register_key_200_response_user", function()
  local openapiclient_i___2fa___register_key_200_response_user = require "openapiclient.model.i___2fa___register_key_200_response_user"

  -- unit tests for the property 'id'
  describe("property id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'name'
  describe("property name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'display_name'
  describe("property display_name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
