--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.notes___schedule___create_request_schedule_note
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("notes___schedule___create_request_schedule_note", function()
  local openapiclient_notes___schedule___create_request_schedule_note = require "openapiclient.model.notes___schedule___create_request_schedule_note"

  -- unit tests for the property 'scheduled_at'
  describe("property scheduled_at test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
