--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.role_all_of_policies_any_of_value
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("role_all_of_policies_any_of_value", function()
  local openapiclient_role_all_of_policies_any_of_value = require "openapiclient.model.role_all_of_policies_any_of_value"

end)
