--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___avatar_decorations___update_request class
local admin___avatar_decorations___update_request = {}
local admin___avatar_decorations___update_request_mt = {
	__name = "admin___avatar_decorations___update_request";
	__index = admin___avatar_decorations___update_request;
}

local function cast_admin___avatar_decorations___update_request(t)
	return setmetatable(t, admin___avatar_decorations___update_request_mt)
end

local function new_admin___avatar_decorations___update_request(id, name, description, url, role_ids_that_can_be_used_this_decoration)
	return cast_admin___avatar_decorations___update_request({
		["id"] = id;
		["name"] = name;
		["description"] = description;
		["url"] = url;
		["roleIdsThatCanBeUsedThisDecoration"] = role_ids_that_can_be_used_this_decoration;
	})
end

return {
	cast = cast_admin___avatar_decorations___update_request;
	new = new_admin___avatar_decorations___update_request;
}
