--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___cw_user_request class
local admin___cw_user_request = {}
local admin___cw_user_request_mt = {
	__name = "admin___cw_user_request",
	__index = admin___cw_user_request,
}

local function cast_admin___cw_user_request(t)
	return setmetatable(t, admin___cw_user_request_mt)
end

local function new_admin___cw_user_request(user_id, cw)
	return cast_admin___cw_user_request({
		["userId"] = user_id,
		["cw"] = cw,
	})
end

return {
	cast = cast_admin___cw_user_request,
	new = new_admin___cw_user_request,
}
