--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___server_info_200_response_mem class
local admin___server_info_200_response_mem = {}
local admin___server_info_200_response_mem_mt = {
	__name = "admin___server_info_200_response_mem",
	__index = admin___server_info_200_response_mem,
}

local function cast_admin___server_info_200_response_mem(t)
	return setmetatable(t, admin___server_info_200_response_mem_mt)
end

local function new_admin___server_info_200_response_mem(total)
	return cast_admin___server_info_200_response_mem({
		["total"] = total,
	})
end

return {
	cast = cast_admin___server_info_200_response_mem,
	new = new_admin___server_info_200_response_mem,
}
