--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___relays___add_request class
local admin___relays___add_request = {}
local admin___relays___add_request_mt = {
	__name = "admin___relays___add_request",
	__index = admin___relays___add_request,
}

local function cast_admin___relays___add_request(t)
	return setmetatable(t, admin___relays___add_request_mt)
end

local function new_admin___relays___add_request(inbox)
	return cast_admin___relays___add_request({
		["inbox"] = inbox,
	})
end

return {
	cast = cast_admin___relays___add_request,
	new = new_admin___relays___add_request,
}
