--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___accounts___find_by_email_request class
local admin___accounts___find_by_email_request = {}
local admin___accounts___find_by_email_request_mt = {
	__name = "admin___accounts___find_by_email_request";
	__index = admin___accounts___find_by_email_request;
}

local function cast_admin___accounts___find_by_email_request(t)
	return setmetatable(t, admin___accounts___find_by_email_request_mt)
end

local function new_admin___accounts___find_by_email_request(email)
	return cast_admin___accounts___find_by_email_request({
		["email"] = email;
	})
end

return {
	cast = cast_admin___accounts___find_by_email_request;
	new = new_admin___accounts___find_by_email_request;
}
