--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___drive___show_file_request class
local admin___drive___show_file_request = {}
local admin___drive___show_file_request_mt = {
	__name = "admin___drive___show_file_request",
	__index = admin___drive___show_file_request,
}

local function cast_admin___drive___show_file_request(t)
	return setmetatable(t, admin___drive___show_file_request_mt)
end

local function new_admin___drive___show_file_request(file_id, url)
	return cast_admin___drive___show_file_request({
		["fileId"] = file_id,
		["url"] = url,
	})
end

return {
	cast = cast_admin___drive___show_file_request,
	new = new_admin___drive___show_file_request,
}
