--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___emoji___copy_request class
local admin___emoji___copy_request = {}
local admin___emoji___copy_request_mt = {
	__name = "admin___emoji___copy_request",
	__index = admin___emoji___copy_request,
}

local function cast_admin___emoji___copy_request(t)
	return setmetatable(t, admin___emoji___copy_request_mt)
end

local function new_admin___emoji___copy_request(emoji_id)
	return cast_admin___emoji___copy_request({
		["emojiId"] = emoji_id,
	})
end

return {
	cast = cast_admin___emoji___copy_request,
	new = new_admin___emoji___copy_request,
}
