--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___roles___unassign_request class
local admin___roles___unassign_request = {}
local admin___roles___unassign_request_mt = {
	__name = "admin___roles___unassign_request";
	__index = admin___roles___unassign_request;
}

local function cast_admin___roles___unassign_request(t)
	return setmetatable(t, admin___roles___unassign_request_mt)
end

local function new_admin___roles___unassign_request(role_id, user_id)
	return cast_admin___roles___unassign_request({
		["roleId"] = role_id;
		["userId"] = user_id;
	})
end

return {
	cast = cast_admin___roles___unassign_request;
	new = new_admin___roles___unassign_request;
}
