--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___accounts___create_200_response class
local admin___accounts___create_200_response = {}
local admin___accounts___create_200_response_mt = {
	__name = "admin___accounts___create_200_response",
	__index = admin___accounts___create_200_response,
}

local function cast_admin___accounts___create_200_response(t)
	return setmetatable(t, admin___accounts___create_200_response_mt)
end

local function new_admin___accounts___create_200_response(token)
	return cast_admin___accounts___create_200_response({
		["token"] = token,
	})
end

return {
	cast = cast_admin___accounts___create_200_response,
	new = new_admin___accounts___create_200_response,
}
