--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___federation___delete_all_files_request class
local admin___federation___delete_all_files_request = {}
local admin___federation___delete_all_files_request_mt = {
	__name = "admin___federation___delete_all_files_request";
	__index = admin___federation___delete_all_files_request;
}

local function cast_admin___federation___delete_all_files_request(t)
	return setmetatable(t, admin___federation___delete_all_files_request_mt)
end

local function new_admin___federation___delete_all_files_request(host)
	return cast_admin___federation___delete_all_files_request({
		["host"] = host;
	})
end

return {
	cast = cast_admin___federation___delete_all_files_request;
	new = new_admin___federation___delete_all_files_request;
}
