--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___update_abuse_user_report_request class
local admin___update_abuse_user_report_request = {}
local admin___update_abuse_user_report_request_mt = {
	__name = "admin___update_abuse_user_report_request";
	__index = admin___update_abuse_user_report_request;
}

local function cast_admin___update_abuse_user_report_request(t)
	return setmetatable(t, admin___update_abuse_user_report_request_mt)
end

local function new_admin___update_abuse_user_report_request(report_id, moderation_note)
	return cast_admin___update_abuse_user_report_request({
		["reportId"] = report_id;
		["moderationNote"] = moderation_note;
	})
end

return {
	cast = cast_admin___update_abuse_user_report_request;
	new = new_admin___update_abuse_user_report_request;
}
