--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___emoji___list_request class
local admin___emoji___list_request = {}
local admin___emoji___list_request_mt = {
	__name = "admin___emoji___list_request";
	__index = admin___emoji___list_request;
}

local function cast_admin___emoji___list_request(t)
	return setmetatable(t, admin___emoji___list_request_mt)
end

local function new_admin___emoji___list_request(query, limit, offset, since_id, until_id)
	return cast_admin___emoji___list_request({
		["query"] = query;
		["limit"] = limit;
		["offset"] = offset;
		["sinceId"] = since_id;
		["untilId"] = until_id;
	})
end

return {
	cast = cast_admin___emoji___list_request;
	new = new_admin___emoji___list_request;
}
