--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___invite___create_request class
local admin___invite___create_request = {}
local admin___invite___create_request_mt = {
	__name = "admin___invite___create_request",
	__index = admin___invite___create_request,
}

local function cast_admin___invite___create_request(t)
	return setmetatable(t, admin___invite___create_request_mt)
end

local function new_admin___invite___create_request(count, expires_at)
	return cast_admin___invite___create_request({
		["count"] = count,
		["expiresAt"] = expires_at,
	})
end

return {
	cast = cast_admin___invite___create_request,
	new = new_admin___invite___create_request,
}
