--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___reset_password_200_response class
local admin___reset_password_200_response = {}
local admin___reset_password_200_response_mt = {
	__name = "admin___reset_password_200_response";
	__index = admin___reset_password_200_response;
}

local function cast_admin___reset_password_200_response(t)
	return setmetatable(t, admin___reset_password_200_response_mt)
end

local function new_admin___reset_password_200_response(password)
	return cast_admin___reset_password_200_response({
		["password"] = password;
	})
end

return {
	cast = cast_admin___reset_password_200_response;
	new = new_admin___reset_password_200_response;
}
