--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___accounts___create_request class
local admin___accounts___create_request = {}
local admin___accounts___create_request_mt = {
	__name = "admin___accounts___create_request",
	__index = admin___accounts___create_request,
}

local function cast_admin___accounts___create_request(t)
	return setmetatable(t, admin___accounts___create_request_mt)
end

local function new_admin___accounts___create_request(username, password, setup_password)
	return cast_admin___accounts___create_request({
		["username"] = username,
		["password"] = password,
		["setupPassword"] = setup_password,
	})
end

return {
	cast = cast_admin___accounts___create_request,
	new = new_admin___accounts___create_request,
}
