--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___announcements___create_request class
local admin___announcements___create_request = {}
local admin___announcements___create_request_mt = {
	__name = "admin___announcements___create_request",
	__index = admin___announcements___create_request,
}

local function cast_admin___announcements___create_request(t)
	return setmetatable(t, admin___announcements___create_request_mt)
end

local function new_admin___announcements___create_request(title, text, image_url, icon, display, for_existing_users, silence, need_confirmation_to_read, user_id)
	return cast_admin___announcements___create_request({
		["title"] = title,
		["text"] = text,
		["imageUrl"] = image_url,
		["icon"] = icon,
		["display"] = display,
		["forExistingUsers"] = for_existing_users,
		["silence"] = silence,
		["needConfirmationToRead"] = need_confirmation_to_read,
		["userId"] = user_id,
	})
end

return {
	cast = cast_admin___announcements___create_request,
	new = new_admin___announcements___create_request,
}
