--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___show_user_200_response_notification_recieve_config_note_one_of class
local admin___show_user_200_response_notification_recieve_config_note_one_of = {}
local admin___show_user_200_response_notification_recieve_config_note_one_of_mt = {
	__name = "admin___show_user_200_response_notification_recieve_config_note_one_of",
	__index = admin___show_user_200_response_notification_recieve_config_note_one_of,
}

local function cast_admin___show_user_200_response_notification_recieve_config_note_one_of(t)
	return setmetatable(t, admin___show_user_200_response_notification_recieve_config_note_one_of_mt)
end

local function new_admin___show_user_200_response_notification_recieve_config_note_one_of(type)
	return cast_admin___show_user_200_response_notification_recieve_config_note_one_of({
		["type"] = type,
	})
end

return {
	cast = cast_admin___show_user_200_response_notification_recieve_config_note_one_of,
	new = new_admin___show_user_200_response_notification_recieve_config_note_one_of,
}
