--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- admin___send_email_request class
local admin___send_email_request = {}
local admin___send_email_request_mt = {
	__name = "admin___send_email_request";
	__index = admin___send_email_request;
}

local function cast_admin___send_email_request(t)
	return setmetatable(t, admin___send_email_request_mt)
end

local function new_admin___send_email_request(to, subject, text)
	return cast_admin___send_email_request({
		["to"] = to;
		["subject"] = subject;
		["text"] = text;
	})
end

return {
	cast = cast_admin___send_email_request;
	new = new_admin___send_email_request;
}
