--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- antenna class
local antenna = {}
local antenna_mt = {
	__name = "antenna",
	__index = antenna,
}

local function cast_antenna(t)
	return setmetatable(t, antenna_mt)
end

local function new_antenna(id, created_at, name, keywords, exclude_keywords, src, user_list_id, users, case_sensitive, local_only, exclude_bots, with_replies, with_file, is_active, has_unread_note, notify)
	return cast_antenna({
		["id"] = id,
		["createdAt"] = created_at,
		["name"] = name,
		["keywords"] = keywords,
		["excludeKeywords"] = exclude_keywords,
		["src"] = src,
		["userListId"] = user_list_id,
		["users"] = users,
		["caseSensitive"] = case_sensitive,
		["localOnly"] = local_only,
		["excludeBots"] = exclude_bots,
		["withReplies"] = with_replies,
		["withFile"] = with_file,
		["isActive"] = is_active,
		["hasUnreadNote"] = has_unread_note,
		["notify"] = notify,
	})
end

return {
	cast = cast_antenna,
	new = new_antenna,
}
