--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- blocking class
local blocking = {}
local blocking_mt = {
	__name = "blocking";
	__index = blocking;
}

local function cast_blocking(t)
	return setmetatable(t, blocking_mt)
end

local function new_blocking(id, created_at, blockee_id, blockee)
	return cast_blocking({
		["id"] = id;
		["createdAt"] = created_at;
		["blockeeId"] = blockee_id;
		["blockee"] = blockee;
	})
end

return {
	cast = cast_blocking;
	new = new_blocking;
}
