--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- bubble_game___ranking_request class
local bubble_game___ranking_request = {}
local bubble_game___ranking_request_mt = {
	__name = "bubble_game___ranking_request";
	__index = bubble_game___ranking_request;
}

local function cast_bubble_game___ranking_request(t)
	return setmetatable(t, bubble_game___ranking_request_mt)
end

local function new_bubble_game___ranking_request(game_mode)
	return cast_bubble_game___ranking_request({
		["gameMode"] = game_mode;
	})
end

return {
	cast = cast_bubble_game___ranking_request;
	new = new_bubble_game___ranking_request;
}
