--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- channels___followed_request class
local channels___followed_request = {}
local channels___followed_request_mt = {
	__name = "channels___followed_request",
	__index = channels___followed_request,
}

local function cast_channels___followed_request(t)
	return setmetatable(t, channels___followed_request_mt)
end

local function new_channels___followed_request(since_id, until_id, limit)
	return cast_channels___followed_request({
		["sinceId"] = since_id,
		["untilId"] = until_id,
		["limit"] = limit,
	})
end

return {
	cast = cast_channels___followed_request,
	new = new_channels___followed_request,
}
