--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- channels___create_request class
local channels___create_request = {}
local channels___create_request_mt = {
	__name = "channels___create_request";
	__index = channels___create_request;
}

local function cast_channels___create_request(t)
	return setmetatable(t, channels___create_request_mt)
end

local function new_channels___create_request(name, description, banner_id, color, is_sensitive, allow_renote_to_external)
	return cast_channels___create_request({
		["name"] = name;
		["description"] = description;
		["bannerId"] = banner_id;
		["color"] = color;
		["isSensitive"] = is_sensitive;
		["allowRenoteToExternal"] = allow_renote_to_external;
	})
end

return {
	cast = cast_channels___create_request;
	new = new_channels___create_request;
}
