--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- charts___instance_200_response_requests class
local charts___instance_200_response_requests = {}
local charts___instance_200_response_requests_mt = {
	__name = "charts___instance_200_response_requests";
	__index = charts___instance_200_response_requests;
}

local function cast_charts___instance_200_response_requests(t)
	return setmetatable(t, charts___instance_200_response_requests_mt)
end

local function new_charts___instance_200_response_requests(failed, succeeded, received)
	return cast_charts___instance_200_response_requests({
		["failed"] = failed;
		["succeeded"] = succeeded;
		["received"] = received;
	})
end

return {
	cast = cast_charts___instance_200_response_requests;
	new = new_charts___instance_200_response_requests;
}
