--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- drive___files___check_existence_request class
local drive___files___check_existence_request = {}
local drive___files___check_existence_request_mt = {
	__name = "drive___files___check_existence_request",
	__index = drive___files___check_existence_request,
}

local function cast_drive___files___check_existence_request(t)
	return setmetatable(t, drive___files___check_existence_request_mt)
end

local function new_drive___files___check_existence_request(md5)
	return cast_drive___files___check_existence_request({
		["md5"] = md5,
	})
end

return {
	cast = cast_drive___files___check_existence_request,
	new = new_drive___files___check_existence_request,
}
