--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- email_address___available_200_response class
local email_address___available_200_response = {}
local email_address___available_200_response_mt = {
	__name = "email_address___available_200_response",
	__index = email_address___available_200_response,
}

local function cast_email_address___available_200_response(t)
	return setmetatable(t, email_address___available_200_response_mt)
end

local function new_email_address___available_200_response(available, reason)
	return cast_email_address___available_200_response({
		["available"] = available,
		["reason"] = reason,
	})
end

return {
	cast = cast_email_address___available_200_response,
	new = new_email_address___available_200_response,
}
