--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- federation___users_request class
local federation___users_request = {}
local federation___users_request_mt = {
	__name = "federation___users_request";
	__index = federation___users_request;
}

local function cast_federation___users_request(t)
	return setmetatable(t, federation___users_request_mt)
end

local function new_federation___users_request(host, since_id, until_id, limit)
	return cast_federation___users_request({
		["host"] = host;
		["sinceId"] = since_id;
		["untilId"] = until_id;
		["limit"] = limit;
	})
end

return {
	cast = cast_federation___users_request;
	new = new_federation___users_request;
}
