--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- fetch_external_resources_request class
local fetch_external_resources_request = {}
local fetch_external_resources_request_mt = {
	__name = "fetch_external_resources_request",
	__index = fetch_external_resources_request,
}

local function cast_fetch_external_resources_request(t)
	return setmetatable(t, fetch_external_resources_request_mt)
end

local function new_fetch_external_resources_request(url, hash)
	return cast_fetch_external_resources_request({
		["url"] = url,
		["hash"] = hash,
	})
end

return {
	cast = cast_fetch_external_resources_request,
	new = new_fetch_external_resources_request,
}
