--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- flash___delete_request class
local flash___delete_request = {}
local flash___delete_request_mt = {
	__name = "flash___delete_request",
	__index = flash___delete_request,
}

local function cast_flash___delete_request(t)
	return setmetatable(t, flash___delete_request_mt)
end

local function new_flash___delete_request(flash_id)
	return cast_flash___delete_request({
		["flashId"] = flash_id,
	})
end

return {
	cast = cast_flash___delete_request,
	new = new_flash___delete_request,
}
