--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- flash___my_request class
local flash___my_request = {}
local flash___my_request_mt = {
	__name = "flash___my_request",
	__index = flash___my_request,
}

local function cast_flash___my_request(t)
	return setmetatable(t, flash___my_request_mt)
end

local function new_flash___my_request(limit, since_id, until_id)
	return cast_flash___my_request({
		["limit"] = limit,
		["sinceId"] = since_id,
		["untilId"] = until_id,
	})
end

return {
	cast = cast_flash___my_request,
	new = new_flash___my_request,
}
