--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- flash___featured_request class
local flash___featured_request = {}
local flash___featured_request_mt = {
	__name = "flash___featured_request",
	__index = flash___featured_request,
}

local function cast_flash___featured_request(t)
	return setmetatable(t, flash___featured_request_mt)
end

local function new_flash___featured_request(offset, limit)
	return cast_flash___featured_request({
		["offset"] = offset,
		["limit"] = limit,
	})
end

return {
	cast = cast_flash___featured_request,
	new = new_flash___featured_request,
}
