--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- following___create_request class
local following___create_request = {}
local following___create_request_mt = {
	__name = "following___create_request",
	__index = following___create_request,
}

local function cast_following___create_request(t)
	return setmetatable(t, following___create_request_mt)
end

local function new_following___create_request(user_id, with_replies)
	return cast_following___create_request({
		["userId"] = user_id,
		["withReplies"] = with_replies,
	})
end

return {
	cast = cast_following___create_request,
	new = new_following___create_request,
}
