--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- gallery___posts___update_request class
local gallery___posts___update_request = {}
local gallery___posts___update_request_mt = {
	__name = "gallery___posts___update_request";
	__index = gallery___posts___update_request;
}

local function cast_gallery___posts___update_request(t)
	return setmetatable(t, gallery___posts___update_request_mt)
end

local function new_gallery___posts___update_request(post_id, title, description, file_ids, is_sensitive)
	return cast_gallery___posts___update_request({
		["postId"] = post_id;
		["title"] = title;
		["description"] = description;
		["fileIds"] = file_ids;
		["isSensitive"] = is_sensitive;
	})
end

return {
	cast = cast_gallery___posts___update_request;
	new = new_gallery___posts___update_request;
}
