--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- get_online_users_count_200_response class
local get_online_users_count_200_response = {}
local get_online_users_count_200_response_mt = {
	__name = "get_online_users_count_200_response";
	__index = get_online_users_count_200_response;
}

local function cast_get_online_users_count_200_response(t)
	return setmetatable(t, get_online_users_count_200_response_mt)
end

local function new_get_online_users_count_200_response(count)
	return cast_get_online_users_count_200_response({
		["count"] = count;
	})
end

return {
	cast = cast_get_online_users_count_200_response;
	new = new_get_online_users_count_200_response;
}
