--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- i___2fa___register_key_200_response_exclude_credentials_inner class
local i___2fa___register_key_200_response_exclude_credentials_inner = {}
local i___2fa___register_key_200_response_exclude_credentials_inner_mt = {
	__name = "i___2fa___register_key_200_response_exclude_credentials_inner",
	__index = i___2fa___register_key_200_response_exclude_credentials_inner,
}

local function cast_i___2fa___register_key_200_response_exclude_credentials_inner(t)
	return setmetatable(t, i___2fa___register_key_200_response_exclude_credentials_inner_mt)
end

local function new_i___2fa___register_key_200_response_exclude_credentials_inner(id, type, transports)
	return cast_i___2fa___register_key_200_response_exclude_credentials_inner({
		["id"] = id,
		["type"] = type,
		["transports"] = transports,
	})
end

return {
	cast = cast_i___2fa___register_key_200_response_exclude_credentials_inner,
	new = new_i___2fa___register_key_200_response_exclude_credentials_inner,
}
