--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- i___registry___scopes_with_domain_200_response_inner class
local i___registry___scopes_with_domain_200_response_inner = {}
local i___registry___scopes_with_domain_200_response_inner_mt = {
	__name = "i___registry___scopes_with_domain_200_response_inner";
	__index = i___registry___scopes_with_domain_200_response_inner;
}

local function cast_i___registry___scopes_with_domain_200_response_inner(t)
	return setmetatable(t, i___registry___scopes_with_domain_200_response_inner_mt)
end

local function new_i___registry___scopes_with_domain_200_response_inner(scopes, domain)
	return cast_i___registry___scopes_with_domain_200_response_inner({
		["scopes"] = scopes;
		["domain"] = domain;
	})
end

return {
	cast = cast_i___registry___scopes_with_domain_200_response_inner;
	new = new_i___registry___scopes_with_domain_200_response_inner;
}
