--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- i___page_likes_200_response_inner class
local i___page_likes_200_response_inner = {}
local i___page_likes_200_response_inner_mt = {
	__name = "i___page_likes_200_response_inner",
	__index = i___page_likes_200_response_inner,
}

local function cast_i___page_likes_200_response_inner(t)
	return setmetatable(t, i___page_likes_200_response_inner_mt)
end

local function new_i___page_likes_200_response_inner(id, page)
	return cast_i___page_likes_200_response_inner({
		["id"] = id,
		["page"] = page,
	})
end

return {
	cast = cast_i___page_likes_200_response_inner,
	new = new_i___page_likes_200_response_inner,
}
