--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- i___2fa___key_done_request class
local i___2fa___key_done_request = {}
local i___2fa___key_done_request_mt = {
	__name = "i___2fa___key_done_request",
	__index = i___2fa___key_done_request,
}

local function cast_i___2fa___key_done_request(t)
	return setmetatable(t, i___2fa___key_done_request_mt)
end

local function new_i___2fa___key_done_request(password, token, name, credential)
	return cast_i___2fa___key_done_request({
		["password"] = password,
		["token"] = token,
		["name"] = name,
		["credential"] = credential,
	})
end

return {
	cast = cast_i___2fa___key_done_request,
	new = new_i___2fa___key_done_request,
}
