--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- i___webhooks___create_request class
local i___webhooks___create_request = {}
local i___webhooks___create_request_mt = {
	__name = "i___webhooks___create_request";
	__index = i___webhooks___create_request;
}

local function cast_i___webhooks___create_request(t)
	return setmetatable(t, i___webhooks___create_request_mt)
end

local function new_i___webhooks___create_request(name, url, secret, on)
	return cast_i___webhooks___create_request({
		["name"] = name;
		["url"] = url;
		["secret"] = secret;
		["on"] = on;
	})
end

return {
	cast = cast_i___webhooks___create_request;
	new = new_i___webhooks___create_request;
}
