--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- invite___delete_request class
local invite___delete_request = {}
local invite___delete_request_mt = {
	__name = "invite___delete_request";
	__index = invite___delete_request;
}

local function cast_invite___delete_request(t)
	return setmetatable(t, invite___delete_request_mt)
end

local function new_invite___delete_request(invite_id)
	return cast_invite___delete_request({
		["inviteId"] = invite_id;
	})
end

return {
	cast = cast_invite___delete_request;
	new = new_invite___delete_request;
}
