--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- me_detailed_only class
local me_detailed_only = {}
local me_detailed_only_mt = {
	__name = "me_detailed_only",
	__index = me_detailed_only,
}

local function cast_me_detailed_only(t)
	return setmetatable(t, me_detailed_only_mt)
end

local function new_me_detailed_only(avatar_id, banner_id, background_id, followed_message, is_moderator, is_admin, inject_featured_note, receive_announcement_email, always_mark_nsfw, default_sensitive, auto_sensitive, careful_bot, auto_accept_followed, no_crawle, prevent_ai_learning, is_explorable, is_deleted, two_factor_backup_codes_stock, hide_online_status, has_unread_specified_notes, has_unread_mentions, has_unread_announcement, unread_announcements, has_unread_antenna, has_unread_channel, has_unread_notification, has_pending_received_follow_request, has_pending_sent_follow_request, unread_notifications_count, muted_words, hard_muted_words, muted_instances, notification_recieve_config, email_notification_types, achievements, logged_in_days, policies, two_factor_enabled, use_password_less_login, security_keys, email, email_verified, security_keys_list, default_cw, default_cw_priority)
	return cast_me_detailed_only({
		["avatarId"] = avatar_id,
		["bannerId"] = banner_id,
		["backgroundId"] = background_id,
		["followedMessage"] = followed_message,
		["isModerator"] = is_moderator,
		["isAdmin"] = is_admin,
		["injectFeaturedNote"] = inject_featured_note,
		["receiveAnnouncementEmail"] = receive_announcement_email,
		["alwaysMarkNsfw"] = always_mark_nsfw,
		["defaultSensitive"] = default_sensitive,
		["autoSensitive"] = auto_sensitive,
		["carefulBot"] = careful_bot,
		["autoAcceptFollowed"] = auto_accept_followed,
		["noCrawle"] = no_crawle,
		["preventAiLearning"] = prevent_ai_learning,
		["isExplorable"] = is_explorable,
		["isDeleted"] = is_deleted,
		["twoFactorBackupCodesStock"] = two_factor_backup_codes_stock,
		["hideOnlineStatus"] = hide_online_status,
		["hasUnreadSpecifiedNotes"] = has_unread_specified_notes,
		["hasUnreadMentions"] = has_unread_mentions,
		["hasUnreadAnnouncement"] = has_unread_announcement,
		["unreadAnnouncements"] = unread_announcements,
		["hasUnreadAntenna"] = has_unread_antenna,
		["hasUnreadChannel"] = has_unread_channel,
		["hasUnreadNotification"] = has_unread_notification,
		["hasPendingReceivedFollowRequest"] = has_pending_received_follow_request,
		["hasPendingSentFollowRequest"] = has_pending_sent_follow_request,
		["unreadNotificationsCount"] = unread_notifications_count,
		["mutedWords"] = muted_words,
		["hardMutedWords"] = hard_muted_words,
		["mutedInstances"] = muted_instances,
		["notificationRecieveConfig"] = notification_recieve_config,
		["emailNotificationTypes"] = email_notification_types,
		["achievements"] = achievements,
		["loggedInDays"] = logged_in_days,
		["policies"] = policies,
		["twoFactorEnabled"] = two_factor_enabled,
		["usePasswordLessLogin"] = use_password_less_login,
		["securityKeys"] = security_keys,
		["email"] = email,
		["emailVerified"] = email_verified,
		["securityKeysList"] = security_keys_list,
		["defaultCW"] = default_cw,
		["defaultCWPriority"] = default_cw_priority,
	})
end

return {
	cast = cast_me_detailed_only,
	new = new_me_detailed_only,
}
