--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- notes___unrenote_request class
local notes___unrenote_request = {}
local notes___unrenote_request_mt = {
	__name = "notes___unrenote_request",
	__index = notes___unrenote_request,
}

local function cast_notes___unrenote_request(t)
	return setmetatable(t, notes___unrenote_request_mt)
end

local function new_notes___unrenote_request(note_id, quote)
	return cast_notes___unrenote_request({
		["noteId"] = note_id,
		["quote"] = quote,
	})
end

return {
	cast = cast_notes___unrenote_request,
	new = new_notes___unrenote_request,
}
