--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- notes___create_200_response class
local notes___create_200_response = {}
local notes___create_200_response_mt = {
	__name = "notes___create_200_response",
	__index = notes___create_200_response,
}

local function cast_notes___create_200_response(t)
	return setmetatable(t, notes___create_200_response_mt)
end

local function new_notes___create_200_response(created_note)
	return cast_notes___create_200_response({
		["createdNote"] = created_note,
	})
end

return {
	cast = cast_notes___create_200_response,
	new = new_notes___create_200_response,
}
