--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- notes___polls___recommendation_request class
local notes___polls___recommendation_request = {}
local notes___polls___recommendation_request_mt = {
	__name = "notes___polls___recommendation_request";
	__index = notes___polls___recommendation_request;
}

local function cast_notes___polls___recommendation_request(t)
	return setmetatable(t, notes___polls___recommendation_request_mt)
end

local function new_notes___polls___recommendation_request(limit, offset, exclude_channels)
	return cast_notes___polls___recommendation_request({
		["limit"] = limit;
		["offset"] = offset;
		["excludeChannels"] = exclude_channels;
	})
end

return {
	cast = cast_notes___polls___recommendation_request;
	new = new_notes___polls___recommendation_request;
}
