--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- notes_request class
local notes_request = {}
local notes_request_mt = {
	__name = "notes_request";
	__index = notes_request;
}

local function cast_notes_request(t)
	return setmetatable(t, notes_request_mt)
end

local function new_notes_request(Local_, reply, renote, with_files, poll, limit, since_id, until_id)
	return cast_notes_request({
		["local"] = Local_;
		["reply"] = reply;
		["renote"] = renote;
		["withFiles"] = with_files;
		["poll"] = poll;
		["limit"] = limit;
		["sinceId"] = since_id;
		["untilId"] = until_id;
	})
end

return {
	cast = cast_notes_request;
	new = new_notes_request;
}
