--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- note_poll_choices_inner class
local note_poll_choices_inner = {}
local note_poll_choices_inner_mt = {
	__name = "note_poll_choices_inner",
	__index = note_poll_choices_inner,
}

local function cast_note_poll_choices_inner(t)
	return setmetatable(t, note_poll_choices_inner_mt)
end

local function new_note_poll_choices_inner(is_voted, text, votes)
	return cast_note_poll_choices_inner({
		["isVoted"] = is_voted,
		["text"] = text,
		["votes"] = votes,
	})
end

return {
	cast = cast_note_poll_choices_inner,
	new = new_note_poll_choices_inner,
}
