--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- notification_one_of_18 class
local notification_one_of_18 = {}
local notification_one_of_18_mt = {
	__name = "notification_one_of_18";
	__index = notification_one_of_18;
}

local function cast_notification_one_of_18(t)
	return setmetatable(t, notification_one_of_18_mt)
end

local function new_notification_one_of_18(id, created_at, type, note, reactions)
	return cast_notification_one_of_18({
		["id"] = id;
		["createdAt"] = created_at;
		["type"] = type;
		["note"] = note;
		["reactions"] = reactions;
	})
end

return {
	cast = cast_notification_one_of_18;
	new = new_notification_one_of_18;
}
