--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- page_block class
local page_block = {}
local page_block_mt = {
	__name = "page_block",
	__index = page_block,
}

local function cast_page_block(t)
	return setmetatable(t, page_block_mt)
end

local function new_page_block(id, type, text, title, children, file_id, detailed, note)
	return cast_page_block({
		["id"] = id,
		["type"] = type,
		["text"] = text,
		["title"] = title,
		["children"] = children,
		["fileId"] = file_id,
		["detailed"] = detailed,
		["note"] = note,
	})
end

return {
	cast = cast_page_block,
	new = new_page_block,
}
