--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- page_block_one_of class
local page_block_one_of = {}
local page_block_one_of_mt = {
	__name = "page_block_one_of";
	__index = page_block_one_of;
}

local function cast_page_block_one_of(t)
	return setmetatable(t, page_block_one_of_mt)
end

local function new_page_block_one_of(id, type, text)
	return cast_page_block_one_of({
		["id"] = id;
		["type"] = type;
		["text"] = text;
	})
end

return {
	cast = cast_page_block_one_of;
	new = new_page_block_one_of;
}
