--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- pages___create_request class
local pages___create_request = {}
local pages___create_request_mt = {
	__name = "pages___create_request",
	__index = pages___create_request,
}

local function cast_pages___create_request(t)
	return setmetatable(t, pages___create_request_mt)
end

local function new_pages___create_request(title, name, summary, content, variables, script, eye_catching_image_id, font, align_center, hide_title_when_pinned)
	return cast_pages___create_request({
		["title"] = title,
		["name"] = name,
		["summary"] = summary,
		["content"] = content,
		["variables"] = variables,
		["script"] = script,
		["eyeCatchingImageId"] = eye_catching_image_id,
		["font"] = font,
		["alignCenter"] = align_center,
		["hideTitleWhenPinned"] = hide_title_when_pinned,
	})
end

return {
	cast = cast_pages___create_request,
	new = new_pages___create_request,
}
