--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- pages___delete_request class
local pages___delete_request = {}
local pages___delete_request_mt = {
	__name = "pages___delete_request";
	__index = pages___delete_request;
}

local function cast_pages___delete_request(t)
	return setmetatable(t, pages___delete_request_mt)
end

local function new_pages___delete_request(page_id)
	return cast_pages___delete_request({
		["pageId"] = page_id;
	})
end

return {
	cast = cast_pages___delete_request;
	new = new_pages___delete_request;
}
