--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- role_all_of_policies_any_of_value class
local role_all_of_policies_any_of_value = {}
local role_all_of_policies_any_of_value_mt = {
	__name = "role_all_of_policies_any_of_value",
	__index = role_all_of_policies_any_of_value,
}

local function cast_role_all_of_policies_any_of_value(t)
	return setmetatable(t, role_all_of_policies_any_of_value_mt)
end

local function new_role_all_of_policies_any_of_value()
	return cast_role_all_of_policies_any_of_value({
	})
end

return {
	cast = cast_role_all_of_policies_any_of_value,
	new = new_role_all_of_policies_any_of_value,
}
