--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- server_info_200_response_fs class
local server_info_200_response_fs = {}
local server_info_200_response_fs_mt = {
	__name = "server_info_200_response_fs";
	__index = server_info_200_response_fs;
}

local function cast_server_info_200_response_fs(t)
	return setmetatable(t, server_info_200_response_fs_mt)
end

local function new_server_info_200_response_fs(total, used)
	return cast_server_info_200_response_fs({
		["total"] = total;
		["used"] = used;
	})
end

return {
	cast = cast_server_info_200_response_fs;
	new = new_server_info_200_response_fs;
}
