--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- sw___register_request class
local sw___register_request = {}
local sw___register_request_mt = {
	__name = "sw___register_request",
	__index = sw___register_request,
}

local function cast_sw___register_request(t)
	return setmetatable(t, sw___register_request_mt)
end

local function new_sw___register_request(endpoint, auth, publickey, send_read_message)
	return cast_sw___register_request({
		["endpoint"] = endpoint,
		["auth"] = auth,
		["publickey"] = publickey,
		["sendReadMessage"] = send_read_message,
	})
end

return {
	cast = cast_sw___register_request,
	new = new_sw___register_request,
}
