--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- users___achievements_200_response_inner class
local users___achievements_200_response_inner = {}
local users___achievements_200_response_inner_mt = {
	__name = "users___achievements_200_response_inner";
	__index = users___achievements_200_response_inner;
}

local function cast_users___achievements_200_response_inner(t)
	return setmetatable(t, users___achievements_200_response_inner_mt)
end

local function new_users___achievements_200_response_inner(name, unlocked_at)
	return cast_users___achievements_200_response_inner({
		["name"] = name;
		["unlockedAt"] = unlocked_at;
	})
end

return {
	cast = cast_users___achievements_200_response_inner;
	new = new_users___achievements_200_response_inner;
}
