--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- users___lists___pull_request class
local users___lists___pull_request = {}
local users___lists___pull_request_mt = {
	__name = "users___lists___pull_request";
	__index = users___lists___pull_request;
}

local function cast_users___lists___pull_request(t)
	return setmetatable(t, users___lists___pull_request_mt)
end

local function new_users___lists___pull_request(list_id, user_id)
	return cast_users___lists___pull_request({
		["listId"] = list_id;
		["userId"] = user_id;
	})
end

return {
	cast = cast_users___lists___pull_request;
	new = new_users___lists___pull_request;
}
