--[[
  Misskey API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 2025.2.2
  
  Generated by: https://openapi-generator.tech
]]

-- users___relation_request_user_id class
local users___relation_request_user_id = {}
local users___relation_request_user_id_mt = {
	__name = "users___relation_request_user_id",
	__index = users___relation_request_user_id,
}

local function cast_users___relation_request_user_id(t)
	return setmetatable(t, users___relation_request_user_id_mt)
end

local function new_users___relation_request_user_id()
	return cast_users___relation_request_user_id({
	})
end

return {
	cast = cast_users___relation_request_user_id,
	new = new_users___relation_request_user_id,
}
